# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'channels' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for channels
  pod 'OneSignal', '>= 2.5.2', '< 3.0'
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/AppBar'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Collections'
  pod 'MaterialComponents/AnimationTiming'
  pod 'MaterialComponents/FlexibleHeader'
  pod 'MaterialComponents/Ink'
  pod 'MaterialComponents/ShadowElevations'
  pod 'MaterialComponents/ShadowLayer'
  pod 'MaterialComponents/Typography'
end

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneSignalNotificationServiceExtension
  pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
